server:
  port: 8071

spring:
  application:
    name: service-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///shop? serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
  jpa:properties:
    hibernate:
      hbm2ddl:
        auto: update  #自动创建数据表  存在就不创建
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect  #方言