server:
  port: 8082

spring:
  application:
    name: service-product
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update  #自动创建数据表  存在就不创建
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect  #方言